### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by Aults1002** [rebel1324/NutScript#153]
Is there a way I can make it where the description creation goes away in the character creator and descriptions are disabled on the server

**Comment by biorisk2** [comment]
A simple fix is to remove the derma for adding a desc on client side character creation derma files, look in the derma folder.

You can also edit the getDesc() command to return "" for descriptions, this should "remove" them.

Also, since this isn't a real "issue" more or a request or suggestion, you could try using the discord which has active people that can help.

**Comment by rebel1324** [comment]
set Desc Limit to 0, I managed to do that in CityRP
