### ISSUE TITLE
T-Posing Combine Models

### ISSUE THREAD

**Issue by AzelOffical** [rebel1324/NutScript#172]
Combine Soldier, Combine Elite, Combine Prison Guard are doing the T-Pose doing certain actions.

https://www.youtube.com/watch?v=1QOPtLY0NAk&feature=youtu.be Here is the video showing the problem.

**Comment by AzelOffical** [comment]
Okey, so when I set the Combine Overwatch to use Player Model, then NPC Models work, but the Player Models don't. I would say that's good, but I don't want to keep setting each new Combine Overwatch play from T-Posing Player Model to NPC Model.

**Comment by SleepyMode** [comment]
They're not meant to walk around without a gun, that's an issue with the model, not with Nutscript.

**Comment by SleepyMode** [comment]
I am very confused by your last sentence.
- You set the Combine Overwatch(I'm assuming the faction??) to use the Player Models in the files.
- NPC Models work(??? what ???)
- But player models don't(?????????????????????????????????)

**Comment by AttyZ** [comment]
The thing about that is that those model animations dont work because the model itself (not nutscript) is broken. This issue is not due to nutscript. I recommend downloading the metropolice pack mod and using the combine model from that, which probably have fixed animations for combine soldiers running without weapons. (Though i'm not 100% sure they do, I am 100% sure this issue is not nutscript's fault though a lua plugin to fix animations might be able to assist the issue, it's not essential)

**Comment by rebel1324** [comment]
Okay if you have problem with Nutscript Core just reopen this issue.
