### ISSUE TITLE
Nutscript chat won't "recieve" text when chatting.

### ISSUE THREAD

**Issue by Theodor02** [rebel1324/NutScript#180]
Whenever I try to write stuff in the included nutscript chat the text I write/post wont show up. I don't receive lua errors or anything. Nutscript commands won't work aswell but  ULX commands still works though. When switching back to the standard gmod chat I can write but the nutscript commands won't work aswell. As I said I don't recieve any lua errors so I have no idea whats wrong.  Either something is wrong or i'm just dumb. Thanks for any help. Edit: Want to note aswell, commands work when I type them in the ingame console.

**Comment by Theodor02** [comment]
Want to note aswell, commands work when I type them in the ingame console.

**Comment by rebel1324** [comment]
so the chat command is not working in Nutscript right?

**Comment by Theodor02** [comment]
Text shows up in the chat if I write say "whatever" in the gmod console the same with the commands example: nut charsetmodel theodor models/bla/bla works But with the nutscript chat plugin enabled the chat doesn't work as stated, no commands get executed or text shows up. The only text that shows up is from ulx and the toolgun aka "actions". If I turn off the nutscript chatplugin with a hook or delete it the chatbox turns into the one sandbox is using.

**Comment by rebel1324** [comment]
strange, can i get to your server? add me on the steam. https://steamcommunity.com/id/GSTM/

**Comment by Theodor02** [comment]
Sent you a friend request, my name is Theodor and I'm using the same picture there as here.

**Comment by Theodor02** [comment]
And made a video example of what I mean aswell https://youtu.be/cJEEj6P_WNc sorrr for the poor quality, I made it in a couple of minutes.

**Comment by rebel1324** [comment]
The issue was caused by the addon Secure Comms W/ Scramble Effect(https://steamcommunity.com/sharedfiles/filedetails/?id=1284940063), It returned the PlayerSay hook whatever it's condition. 

Here is some pro-tip. Do not use `return` if anything in your addon/script is not triggered. just pass through it.

This isn't right
![image](https://user-images.githubusercontent.com/2784192/40062224-baba5c88-5895-11e8-98f2-b0b2b4e7c1e9.png)

This is right.
![image](https://user-images.githubusercontent.com/2784192/40062253-c881644c-5895-11e8-83fa-19ce340095a3.png)
